version: "3.7"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    command: start-dev
    environment:
      KC_LOG_LEVEL: info
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_SPI_EVENTS_LISTENER_WEBHOOK_SERVER_URI: http://localhost
      KC_SPI_EVENTS_LISTENER_WEBHOOK_USERNAME: test
      KC_SPI_EVENTS_LISTENER_WEBHOOK_PASSWORD: password
      KC_SPI_EVENTS_LISTENER_WEBHOOK_USER_EVENT_ENABLE: "true"
      KC_SPI_EVENTS_LISTENER_WEBHOOK_ADMIN_EVENT_ENABLE: "true"
      KC_SPI_EVENTS_LISTENER_WEBHOOK_INCLUDE_USER_EVENTS:
      KC_SPI_EVENTS_LISTENER_WEBHOOK_INCLUDE_ADMIN_EVENTS:
    volumes:
      - ./target/keycloak-event-webhook.jar:/opt/keycloak/providers/keycloak-event-webhook.jar
    depends_on:
      - postgres
    ports:
      - 8080:8080

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
